# Config.pri file version 2.0. Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR = $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        profile {
            INCLUDEPATH += $$quote(/Users/nemory/Desktop/Files/FlurrySDK)

            DEPENDPATH += $$quote(/Users/nemory/Desktop/Files/FlurrySDK)

            LIBS += -lFlurry

            LIBS += $$quote(-L/Users/nemory/Desktop/Files/FlurrySDK/Flurry/armle-v7)

            PRE_TARGETDEPS += $$quote(/Users/nemory/Desktop/Files/FlurrySDK/Flurry/armle-v7)

            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        } else {
            INCLUDEPATH += $$quote(/Users/nemory/Desktop/Files/FlurrySDK)

            DEPENDPATH += $$quote(/Users/nemory/Desktop/Files/FlurrySDK)

            LIBS += -lFlurry

            LIBS += $$quote(-L/Users/nemory/Desktop/Files/FlurrySDK/Flurry/armle-v7)

            PRE_TARGETDEPS += $$quote(/Users/nemory/Desktop/Files/FlurrySDK/Flurry/armle-v7)

            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }

    }

    CONFIG(release, debug|release) {
        !profile {
            INCLUDEPATH += $$quote(/Users/nemory/Desktop/Files/FlurrySDK)

            DEPENDPATH += $$quote(/Users/nemory/Desktop/Files/FlurrySDK)

            LIBS += -lFlurry

            LIBS += $$quote(-L/Users/nemory/Desktop/Files/FlurrySDK/Flurry/armle-v7)

            PRE_TARGETDEPS += $$quote(/Users/nemory/Desktop/Files/FlurrySDK/Flurry/armle-v7)

            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

simulator {
    CONFIG(debug, debug|release) {
        !profile {
            INCLUDEPATH += $$quote(/Users/nemory/Desktop/Files/FlurrySDK)

            DEPENDPATH += $$quote(/Users/nemory/Desktop/Files/FlurrySDK)

            LIBS += -lFlurry

            LIBS += $$quote(-L/Users/nemory/Desktop/Files/FlurrySDK/Flurry/x86)

            PRE_TARGETDEPS += $$quote(/Users/nemory/Desktop/Files/FlurrySDK/Flurry/x86)

            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

config_pri_assets {
    OTHER_FILES += \
        $$quote($$BASEDIR/assets/720x1280/images/activeframe.jpg) \
        $$quote($$BASEDIR/assets/720x720/images/activeframe.jpg) \
        $$quote($$BASEDIR/assets/768x1280/images/activeframe.jpg) \
        $$quote($$BASEDIR/assets/VisualStyle.bright/images/circle_cover.png) \
        $$quote($$BASEDIR/assets/VisualStyle.bright/images/circle_cover_big.png) \
        $$quote($$BASEDIR/assets/VisualStyle.bright/images/circle_cover_title.png) \
        $$quote($$BASEDIR/assets/VisualStyle.bright/images/facebook.png) \
        $$quote($$BASEDIR/assets/VisualStyle.bright/images/info.png) \
        $$quote($$BASEDIR/assets/VisualStyle.dark/images/circle_cover.png) \
        $$quote($$BASEDIR/assets/VisualStyle.dark/images/circle_cover_big.png) \
        $$quote($$BASEDIR/assets/VisualStyle.dark/images/circle_cover_title.png) \
        $$quote($$BASEDIR/assets/VisualStyle.dark/images/facebook.png) \
        $$quote($$BASEDIR/assets/VisualStyle.dark/images/info.png) \
        $$quote($$BASEDIR/assets/activeframes/ActiveFrameCover.qml) \
        $$quote($$BASEDIR/assets/components/AlbumItem.qml) \
        $$quote($$BASEDIR/assets/components/AlbumTrackItem.qml) \
        $$quote($$BASEDIR/assets/components/ArtistAlbumItem.qml) \
        $$quote($$BASEDIR/assets/components/ArtistItem.qml) \
        $$quote($$BASEDIR/assets/components/BrowseItem.qml) \
        $$quote($$BASEDIR/assets/components/NemAdvertisement.qml) \
        $$quote($$BASEDIR/assets/components/PlaylistItem.qml) \
        $$quote($$BASEDIR/assets/components/PlaylistTrackItem.qml) \
        $$quote($$BASEDIR/assets/components/PullToRefreshListView.qml) \
        $$quote($$BASEDIR/assets/components/RadioItem.qml) \
        $$quote($$BASEDIR/assets/components/RefreshHeader.qml) \
        $$quote($$BASEDIR/assets/components/SearchResultItem.qml) \
        $$quote($$BASEDIR/assets/components/TrackItem.qml) \
        $$quote($$BASEDIR/assets/components/VideoPlayer.qml) \
        $$quote($$BASEDIR/assets/images/SplashQ10.jpg) \
        $$quote($$BASEDIR/assets/images/SplashZ10.jpg) \
        $$quote($$BASEDIR/assets/images/email.png) \
        $$quote($$BASEDIR/assets/images/icon144.png) \
        $$quote($$BASEDIR/assets/images/icon480.png) \
        $$quote($$BASEDIR/assets/images/info.png) \
        $$quote($$BASEDIR/assets/images/rate.png) \
        $$quote($$BASEDIR/assets/images/refresh.png) \
        $$quote($$BASEDIR/assets/images/settings.png) \
        $$quote($$BASEDIR/assets/images/spotify/addToPlaylist.png) \
        $$quote($$BASEDIR/assets/images/spotify/album.png) \
        $$quote($$BASEDIR/assets/images/spotify/artists.png) \
        $$quote($$BASEDIR/assets/images/spotify/backgroundPhoto.jpg) \
        $$quote($$BASEDIR/assets/images/spotify/bannerTransparent.png) \
        $$quote($$BASEDIR/assets/images/spotify/box.png) \
        $$quote($$BASEDIR/assets/images/spotify/browse.png) \
        $$quote($$BASEDIR/assets/images/spotify/check.png) \
        $$quote($$BASEDIR/assets/images/spotify/download.png) \
        $$quote($$BASEDIR/assets/images/spotify/filter.png) \
        $$quote($$BASEDIR/assets/images/spotify/music.png) \
        $$quote($$BASEDIR/assets/images/spotify/musicBackground.png) \
        $$quote($$BASEDIR/assets/images/spotify/mute.png) \
        $$quote($$BASEDIR/assets/images/spotify/next.png) \
        $$quote($$BASEDIR/assets/images/spotify/pause.png) \
        $$quote($$BASEDIR/assets/images/spotify/pencil.png) \
        $$quote($$BASEDIR/assets/images/spotify/person.png) \
        $$quote($$BASEDIR/assets/images/spotify/play.png) \
        $$quote($$BASEDIR/assets/images/spotify/playlists.png) \
        $$quote($$BASEDIR/assets/images/spotify/plus.png) \
        $$quote($$BASEDIR/assets/images/spotify/prev.png) \
        $$quote($$BASEDIR/assets/images/spotify/radio.png) \
        $$quote($$BASEDIR/assets/images/spotify/repeat.png) \
        $$quote($$BASEDIR/assets/images/spotify/replay.png) \
        $$quote($$BASEDIR/assets/images/spotify/search.png) \
        $$quote($$BASEDIR/assets/images/spotify/shuffle.png) \
        $$quote($$BASEDIR/assets/images/spotify/shuffleButton.png) \
        $$quote($$BASEDIR/assets/images/spotify/shuffleButtonPressed.png) \
        $$quote($$BASEDIR/assets/images/spotify/star.png) \
        $$quote($$BASEDIR/assets/images/spotify/thumbnail.png) \
        $$quote($$BASEDIR/assets/images/spotify/unmute.png) \
        $$quote($$BASEDIR/assets/images/spotify/upload.png) \
        $$quote($$BASEDIR/assets/images/spotify/voice.png) \
        $$quote($$BASEDIR/assets/images/spotify/x.png) \
        $$quote($$BASEDIR/assets/images/stretchableRefresh.png) \
        $$quote($$BASEDIR/assets/main.qml) \
        $$quote($$BASEDIR/assets/pages/AlbumProfile.qml) \
        $$quote($$BASEDIR/assets/pages/Albums.qml) \
        $$quote($$BASEDIR/assets/pages/ArtistProfile.qml) \
        $$quote($$BASEDIR/assets/pages/Artists.qml) \
        $$quote($$BASEDIR/assets/pages/Browse.qml) \
        $$quote($$BASEDIR/assets/pages/NowPlaying.qml) \
        $$quote($$BASEDIR/assets/pages/PlaylistTracks.qml) \
        $$quote($$BASEDIR/assets/pages/Playlists.qml) \
        $$quote($$BASEDIR/assets/pages/Profile.qml) \
        $$quote($$BASEDIR/assets/pages/Radio.qml) \
        $$quote($$BASEDIR/assets/pages/Search.qml) \
        $$quote($$BASEDIR/assets/pages/Songs.qml) \
        $$quote($$BASEDIR/assets/sheets/AboutSheet.qml) \
        $$quote($$BASEDIR/assets/sheets/LoginSheet.qml) \
        $$quote($$BASEDIR/assets/sheets/MainSheet.qml) \
        $$quote($$BASEDIR/assets/sheets/SettingsSheet.qml) \
        $$quote($$BASEDIR/assets/videos/backgroundVideo.mp4)
}

config_pri_source_group1 {
    SOURCES += \
        $$quote($$BASEDIR/src/ActiveFrame/ActiveFrameCover.cpp) \
        $$quote($$BASEDIR/src/Downloader/Downloader.cpp) \
        $$quote($$BASEDIR/src/NemAPI/NemAPI.cpp) \
        $$quote($$BASEDIR/src/NemAdvertisements/NemAdsController.cpp) \
        $$quote($$BASEDIR/src/WebImageView/WebImageView.cpp) \
        $$quote($$BASEDIR/src/applicationui.cpp) \
        $$quote($$BASEDIR/src/main.cpp)

    HEADERS += \
        $$quote($$BASEDIR/src/ActiveFrame/ActiveFrameCover.h) \
        $$quote($$BASEDIR/src/Downloader/Downloader.hpp) \
        $$quote($$BASEDIR/src/NemAPI/NemAPI.hpp) \
        $$quote($$BASEDIR/src/NemAdvertisements/NemAdsController.hpp) \
        $$quote($$BASEDIR/src/WebImageView/WebImageView.hpp) \
        $$quote($$BASEDIR/src/applicationui.hpp)
}

CONFIG += precompile_header

PRECOMPILED_HEADER = $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES += \
        $$quote($$BASEDIR/../src/*.c) \
        $$quote($$BASEDIR/../src/*.c++) \
        $$quote($$BASEDIR/../src/*.cc) \
        $$quote($$BASEDIR/../src/*.cpp) \
        $$quote($$BASEDIR/../src/*.cxx) \
        $$quote($$BASEDIR/../src/ActiveFrame/*.c) \
        $$quote($$BASEDIR/../src/ActiveFrame/*.c++) \
        $$quote($$BASEDIR/../src/ActiveFrame/*.cc) \
        $$quote($$BASEDIR/../src/ActiveFrame/*.cpp) \
        $$quote($$BASEDIR/../src/ActiveFrame/*.cxx) \
        $$quote($$BASEDIR/../src/Downloader/*.c) \
        $$quote($$BASEDIR/../src/Downloader/*.c++) \
        $$quote($$BASEDIR/../src/Downloader/*.cc) \
        $$quote($$BASEDIR/../src/Downloader/*.cpp) \
        $$quote($$BASEDIR/../src/Downloader/*.cxx) \
        $$quote($$BASEDIR/../src/NemAPI/*.c) \
        $$quote($$BASEDIR/../src/NemAPI/*.c++) \
        $$quote($$BASEDIR/../src/NemAPI/*.cc) \
        $$quote($$BASEDIR/../src/NemAPI/*.cpp) \
        $$quote($$BASEDIR/../src/NemAPI/*.cxx) \
        $$quote($$BASEDIR/../src/NemAdvertisements/*.c) \
        $$quote($$BASEDIR/../src/NemAdvertisements/*.c++) \
        $$quote($$BASEDIR/../src/NemAdvertisements/*.cc) \
        $$quote($$BASEDIR/../src/NemAdvertisements/*.cpp) \
        $$quote($$BASEDIR/../src/NemAdvertisements/*.cxx) \
        $$quote($$BASEDIR/../src/WebImageView/*.c) \
        $$quote($$BASEDIR/../src/WebImageView/*.c++) \
        $$quote($$BASEDIR/../src/WebImageView/*.cc) \
        $$quote($$BASEDIR/../src/WebImageView/*.cpp) \
        $$quote($$BASEDIR/../src/WebImageView/*.cxx) \
        $$quote($$BASEDIR/..//*.qml) \
        $$quote($$BASEDIR/..//*.js) \
        $$quote($$BASEDIR/..//*.qs) \
        $$quote($$BASEDIR/../assets/*.qml) \
        $$quote($$BASEDIR/../assets/*.js) \
        $$quote($$BASEDIR/../assets/*.qs) \
        $$quote($$BASEDIR/../assets/720x1280/*.qml) \
        $$quote($$BASEDIR/../assets/720x1280/*.js) \
        $$quote($$BASEDIR/../assets/720x1280/*.qs) \
        $$quote($$BASEDIR/../assets/720x1280/images/*.qml) \
        $$quote($$BASEDIR/../assets/720x1280/images/*.js) \
        $$quote($$BASEDIR/../assets/720x1280/images/*.qs) \
        $$quote($$BASEDIR/../assets/720x720/*.qml) \
        $$quote($$BASEDIR/../assets/720x720/*.js) \
        $$quote($$BASEDIR/../assets/720x720/*.qs) \
        $$quote($$BASEDIR/../assets/720x720/images/*.qml) \
        $$quote($$BASEDIR/../assets/720x720/images/*.js) \
        $$quote($$BASEDIR/../assets/720x720/images/*.qs) \
        $$quote($$BASEDIR/../assets/768x1280/*.qml) \
        $$quote($$BASEDIR/../assets/768x1280/*.js) \
        $$quote($$BASEDIR/../assets/768x1280/*.qs) \
        $$quote($$BASEDIR/../assets/768x1280/images/*.qml) \
        $$quote($$BASEDIR/../assets/768x1280/images/*.js) \
        $$quote($$BASEDIR/../assets/768x1280/images/*.qs) \
        $$quote($$BASEDIR/../assets/VisualStyle.bright/*.qml) \
        $$quote($$BASEDIR/../assets/VisualStyle.bright/*.js) \
        $$quote($$BASEDIR/../assets/VisualStyle.bright/*.qs) \
        $$quote($$BASEDIR/../assets/VisualStyle.bright/images/*.qml) \
        $$quote($$BASEDIR/../assets/VisualStyle.bright/images/*.js) \
        $$quote($$BASEDIR/../assets/VisualStyle.bright/images/*.qs) \
        $$quote($$BASEDIR/../assets/VisualStyle.dark/*.qml) \
        $$quote($$BASEDIR/../assets/VisualStyle.dark/*.js) \
        $$quote($$BASEDIR/../assets/VisualStyle.dark/*.qs) \
        $$quote($$BASEDIR/../assets/VisualStyle.dark/images/*.qml) \
        $$quote($$BASEDIR/../assets/VisualStyle.dark/images/*.js) \
        $$quote($$BASEDIR/../assets/VisualStyle.dark/images/*.qs) \
        $$quote($$BASEDIR/../assets/activeframes/*.qml) \
        $$quote($$BASEDIR/../assets/activeframes/*.js) \
        $$quote($$BASEDIR/../assets/activeframes/*.qs) \
        $$quote($$BASEDIR/../assets/components/*.qml) \
        $$quote($$BASEDIR/../assets/components/*.js) \
        $$quote($$BASEDIR/../assets/components/*.qs) \
        $$quote($$BASEDIR/../assets/dialogs/*.qml) \
        $$quote($$BASEDIR/../assets/dialogs/*.js) \
        $$quote($$BASEDIR/../assets/dialogs/*.qs) \
        $$quote($$BASEDIR/../assets/images/*.qml) \
        $$quote($$BASEDIR/../assets/images/*.js) \
        $$quote($$BASEDIR/../assets/images/*.qs) \
        $$quote($$BASEDIR/../assets/images/spotify/*.qml) \
        $$quote($$BASEDIR/../assets/images/spotify/*.js) \
        $$quote($$BASEDIR/../assets/images/spotify/*.qs) \
        $$quote($$BASEDIR/../assets/pages/*.qml) \
        $$quote($$BASEDIR/../assets/pages/*.js) \
        $$quote($$BASEDIR/../assets/pages/*.qs) \
        $$quote($$BASEDIR/../assets/sheets/*.qml) \
        $$quote($$BASEDIR/../assets/sheets/*.js) \
        $$quote($$BASEDIR/../assets/sheets/*.qs) \
        $$quote($$BASEDIR/../assets/sounds/*.qml) \
        $$quote($$BASEDIR/../assets/sounds/*.js) \
        $$quote($$BASEDIR/../assets/sounds/*.qs) \
        $$quote($$BASEDIR/../assets/videos/*.qml) \
        $$quote($$BASEDIR/../assets/videos/*.js) \
        $$quote($$BASEDIR/../assets/videos/*.qs)

    HEADERS += \
        $$quote($$BASEDIR/../src/*.h) \
        $$quote($$BASEDIR/../src/*.h++) \
        $$quote($$BASEDIR/../src/*.hh) \
        $$quote($$BASEDIR/../src/*.hpp) \
        $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS = $$quote($${TARGET}.ts)
